### ISSUE TITLE
[bundler]: What's the purpose of *.real binaries added by hab build?

### ISSUE THREAD

**Issue by gavindidrichsen** [chef-base-plans/bundler#1]
See issue on core-plans https://github.com/habitat-sh/core-plans/issues/3447 for more information.

There are 2 of these *.real binaries.  One returns an old version of bundler and the other throws an error:

```bash
```bash
/hab/pkgs/core/bundler/2.1.4/20200817093838/bin/bundle.real --version
Bundler version 1.16.6

/hab/pkgs/core/bundler/2.1.4/20200817093838/bin/bundler.real --version
Traceback (most recent call last):
        2: from /hab/pkgs/core/bundler/2.1.4/20200817093838/bin/bundler.real:23:in `<main>'
        1: from /hab/pkgs/core/ruby/2.5.7/20200404130135/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/hab/pkgs/core/ruby/2.5.7/20200404130135/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
[18][default:/src/bundler:1]# 
```
```

**Comment by gavindidrichsen** [comment]
Closing this.  After looking at the binaries, *.real are the originals:

```bash
[23][default:/hab/pkgs/core/bundler/2.1.4/20200817093838/bin:0]# cat bundle
#!/hab/pkgs/core/busybox-static/1.31.0/20200306011713/bin/sh
set -e
if test -n "$DEBUG"; then set -x; fi

export GEM_HOME="/hab/pkgs/core/bundler/2.1.4/20200817093838"
export GEM_PATH="/hab/pkgs/core/bundler/2.1.4/20200817093838"
unset RUBYOPT GEMRC

exec /hab/pkgs/core/ruby/2.5.7/20200404130135/bin/ruby /hab/pkgs/core/bundler/2.1.4/20200817093838/bin/bundle.real $@
[24][default:/hab/pkgs/core/bundler/2.1.4/20200817093838/bin:0]# cat bundle.real 
#!/hab/pkgs/core/ruby/2.5.7/20200404130135/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
```
